### ISSUE TITLE
Getting Error on Vagrant Up.

### ISSUE THREAD

**Issue by brandonkboswell** [MiniCodeMonkey/Vagrant-Laravel-Stack#18]
Getting The Following Error on Vagrant Up

```
  Command: ["hostonlyif", "create"]

  Stderr: 0%...
  Progress state: NS_ERROR_FAILURE
  VBoxManage: error: Failed to create the host-only adapter
  VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory

  VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
  VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 68 of file VBoxManageHostonly.cpp      
```

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Here's the exact behavior
![vagrantissue](https://f.cloud.github.com/assets/921925/2401385/86bf4b24-aa15-11e3-8990-eab163e7c398.gif)

**Comment by MiniCodeMonkey** [comment]
Best. Issue. Ever. That animated gif is the best thing ever.

This looks like an issue I've seen before with an older version of VirtualBox and OS X Mavericks. You'll need to either update VirtualBox or simply start/restart the VirtualBox provider on your computer. (See more here http://stackoverflow.com/questions/18149546/vagrant-up-failed-dev-vboxnetctl-no-such-file-or-directory)

Are you able to use Vagrant otherwise?

**Comment by brandonkboswell** [comment]
Really tells the story right? 

Updating Virtualbox and Running The Command from Stackoverflow Solved This For Me.

Thanks!
